name: Terraform
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  release:
    types: [published]

env:
  DEFAULT_REGION: ap-south-1
  AWS_ACCESS_KEY_ID: localstack
  AWS_SECRET_ACCESS_KEY: localstack
  CI_COMMIT_AUTHOR: mhrznamn068
  CI_COMMIT_EMAIL: mhrznamn068@gmail.com

jobs:
  check-format:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff

  validate:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    strategy:
      matrix: {
        dir: ['examples/test']
      }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: ${{ matrix.dir }}
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.dir }}

  mock-plan:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    strategy:
      matrix: {
        dir: ['examples/test']
      }
    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: apigateway,cloudformation,cloudwatch,dynamodb,es,firehose,iam,kinesis,lambda,route53,redshift,s3,secretsmanager,ses,sns,sqs,ssm,stepfunctions,sts
        ports:
          - 4566:4566
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: ${{ matrix.dir }}
      - name: Terraform Plan (Mock)
        run: terraform plan
        working-directory: ${{ matrix.dir }}

  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Git push release tag
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          
          git tag "${{ github.run_number }}"
          git tag -f "${{ needs.major-version.outputs.version }}" 
          git push "https://${{ env.CI_COMMIT_AUTHOR }}:${{ secrets.TF_DEVEX_COMMIT_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" "${{ github.run_number }}"
          git push "https://${{ env.CI_COMMIT_AUTHOR }}:${{ secrets.TF_DEVEX_COMMIT_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" -f "${{ needs.major-version.outputs.version }}"

  release:
    needs: [ release-tag ]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create GitHub release
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.run_number }}
          fetch-depth: 0

      - name: Generate Release Notes
        run: |
          cd .changes
          sed -e "1{/# /d;}" -e "2{/^$/d;}" ${{ needs.changelog-version.outputs.version }}.md > /tmp/release-notes.txt

      - name: GH Release
        run: |
          gh release create "${{ github.run_number }}" --notes-file /tmp/release-notes.txt --title "${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
